### ISSUE TITLE
filter expression not working?

### ISSUE THREAD

**Issue by rledousa** [h2non/jsonpath-ng#16]
Hi

I have a simple filter which works on http://jsonpath.com. I'm using jsonpath_ng 1.4.3 

Test script:
`from jsonpath_ng import jsonpath
from jsonpath_ng.ext import parse
f = parse('$..[?(@._env=="foo")]').find(data).   # should return only the first object`

Forgot - even though I'm using the ext parser, I'm getting 
File "/Library/Python/2.7/site-packages/jsonpath_ng/parser.py", line 69, in p_error raise Exception('Parse error at %s:%s near token %s (%s)' % (t.lineno, t.col, t.value, t.type)) Exception: Parse error at 1:7 near token ? (?)

Any help is appreciated!!

`data = {
  "wwrc-stg-lom01.someco.com": {
    "_env": "foo",
    "_owner": "samwise_gamgee",
    "_parent": "wwrc-stg-hv1.rtl.someco.com",
    "dns1": "17.34.100.1",
    "dns2": "17.34.100.2",
    "domain": "rtl.someco.com",
    "env": "p",
    "gateway": "10.16.64.1",
    "hostname": "wwrc-stg-lom01",
    "ipaddr": "10.16.64.11",
    "netmask": "255.255.255.0",
    "rollout": "r145",
    "type": "ilo"
  },
  "wwrc-stg-lom05.rtl.someco.com": {
    "_env": "prod",
    "_owner": "Frodo Baggins",
    "_parent": "wwrc-stg-hv5.rtl.someco.com",
    "dns1": "17.34.100.1",
    "dns2": "17.34.100.2",
    "domain": "rtl.someco.com",
    "env": "p",
    "gateway": "10.16.64.1",
    "hostname": "wwrc-stg-lom05",
    "ipaddr": "10.16.64.15",
    "netmask": "255.255.255.0",
    "rollout": "r145",
    "type": "ilo"
  }
}`

**Comment by rledousa** [comment]
It seems like, besides joeyjoey's comment, the problem is that the parser doesn't like a dict of dicts.  In other words, if I change the data to
`data = {'nodes':  [ { "_env": "foo", "_owner": "samwise_gamgee", "_parent": "wwrc-stg-hv1.rtl.someco.com", "dns1": "17.34.100.1", "dns2": "17.34.100.2", "domain": "rtl.someco.com", "env": "p", "gateway": "10.16.64.1", "hostname": "wwrc-stg-lom01", "ipaddr": "10.16.64.11", "netmask": "255.255.255.0", "rollout": "r145", "type": "ilo" }, { "_env": "prod", "_owner": "Frodo Baggins", "_parent": "wwrc-stg-hv5.rtl.someco.com", "dns1": "17.34.100.1", "dns2": "17.34.100.2", "domain": "rtl.someco.com", "env": "p", "gateway": "10.16.64.1", "hostname": "wwrc-stg-lom05", "ipaddr": "10.16.64.15", "netmask": "255.255.255.0", "rollout": "r145", "type": "ilo" } ]}`

then `$..nodes[?(@.env=="prod")] works as expected`

**Comment by Bezoar** [comment]
I took rledousa's comment above and converted it to a test script, which still doesn't work:

`#!/usr/bin/env python

from jsonpath_ng import parse

data = {'nodes': [
        { "_env": "foo",
          "_owner": "samwise_gamgee",
          "_parent": "wwrc-stg-hv1.rtl.someco.com",
          "dns1": "17.34.100.1",
          "dns2": "17.34.100.2",
          "domain": "rtl.someco.com",
          "env": "p",
          "gateway": "10.16.64.1",
	  "hostname": "wwrc-stg-lom01",
          "ipaddr": "10.16.64.11",
          "netmask": "255.255.255.0",
          "rollout": "r145",
          "type": "ilo" },
        { "_env": "prod",
          "_owner": "Frodo Baggins",
          "_parent": "wwrc-stg-hv5.rtl.someco.com",
          "dns1": "17.34.100.1",
          "dns2": "17.34.100.2",
          "domain": "rtl.someco.com",
          "env": "p",
          "gateway": "10.16.64.1",
          "hostname": "wwrc-stg-lom05",
          "ipaddr": "10.16.64.15",
          "netmask": "255.255.255.0",
          "rollout": "r145",
          "type": "ilo" }
        ]}

e = parse('$..nodes[?(@.env=="prod")]')
results = [m.value for m in e.find(data)]
print("Got {} results:".format(len(results)))
for r in results:
    print("\t{}".format(r))`

When I execute this script (in python 2.7), I get this:

`$ ./check3.py
Traceback (most recent call last):
  File "./check3.py", line 11, in <module>
    e = parse('$..nodes[?(@.env=="prod")]')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jsonpath_ng/parser.py", line 14, in parse
    return JsonPathParser().parse(string)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jsonpath_ng/parser.py", line 32, in parse
    return self.parse_token_stream(lexer.tokenize(string))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jsonpath_ng/parser.py", line 55, in parse_token_stream
    return new_parser.parse(lexer = IteratorToTokenStream(token_iterator))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jsonpath_ng/parser.py", line 179, in token
    return next(self.iterator)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jsonpath_ng/lexer.py", line 35, in tokenize
    t = new_lexer.token()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jsonpath_ng/lexer.py", line 167, in t_error
    raise JsonPathLexerError('Error on line %s, col %s: Unexpected character: %s ' % (t.lexer.lineno, t.lexpos - t.lexer.latest_newline, t.value[0]))
jsonpath_ng.lexer.JsonPathLexerError: Error on line 1, col 9: Unexpected character: ?`
