### ISSUE TITLE
Could not build wheels for jsonpath-ng which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by hund030** [h2non/jsonpath-ng#182]
Could not build wheels for jsonpath-ng which use PEP 517 and cannot be installed directly

Is this expected? What should I do to mitigate this?
I didn't meet this error before. Maybe related to the latest release 1.7.0.

Error logs:
```
  Building wheels for collected packages: jsonpath-ng
  
    Building wheel for jsonpath-ng (PEP 517): started
  
    Building wheel for jsonpath-ng (PEP 517): finished with status 'error'
  
    ERROR: Command errored out with exit status 1:
     command: /workspaces/template/.venv/bin/python3 /tmp/tmpcegeok82_in_process.py build_wheel /tmp/tmppzbfdpa_
         cwd: /tmp/pip-install-ummtjf61/jsonpath-ng_5378181bf9f949f58b4f51182c60e264
    Complete output (71 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/jsonpath_ng
    copying jsonpath_ng/parser.py -> build/lib/jsonpath_ng
    copying jsonpath_ng/lexer.py -> build/lib/jsonpath_ng
    copying jsonpath_ng/jsonpath.py -> build/lib/jsonpath_ng
    copying jsonpath_ng/exceptions.py -> build/lib/jsonpath_ng
    copying jsonpath_ng/__init__.py -> build/lib/jsonpath_ng
    creating build/lib/jsonpath_ng/bin
    copying jsonpath_ng/bin/jsonpath.py -> build/lib/jsonpath_ng/bin
    copying jsonpath_ng/bin/__init__.py -> build/lib/jsonpath_ng/bin
    creating build/lib/jsonpath_ng/ext
    copying jsonpath_ng/ext/string.py -> build/lib/jsonpath_ng/ext
    copying jsonpath_ng/ext/parser.py -> build/lib/jsonpath_ng/ext
    copying jsonpath_ng/ext/iterable.py -> build/lib/jsonpath_ng/ext
    copying jsonpath_ng/ext/filter.py -> build/lib/jsonpath_ng/ext
    copying jsonpath_ng/ext/arithmetic.py -> build/lib/jsonpath_ng/ext
    copying jsonpath_ng/ext/__init__.py -> build/lib/jsonpath_ng/ext
    running install
    running install_lib
    Traceback (most recent call last):
      File "/tmp/tmpcegeok82_in_process.py", line 280, in <module>
        main()
      File "/tmp/tmpcegeok82_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpcegeok82_in_process.py", line 204, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 216, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
        self.run_setup()
      File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 5, in <module>
        setuptools.setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 259, in run
        self.run_command('install')
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 578, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
        self.set_undefined_options('install',('install_layout','install_layout'))
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
        setattr(self, dst_option, getattr(src_cmd_obj, src_option))
      File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: install_layout
    ----------------------------------------
    ERROR: Failed building wheel for jsonpath-ng
  
  Failed to build jsonpath-ng
```

**Comment by hund030** [comment]
I resolve the issue by upgrading pip.
