### ISSUE TITLE
filter problem

### ISSUE THREAD

**Issue by sunziyi** [h2non/jsonpath-ng#3]
I try to use filter to find data with "akey"="idcard". Here is my code.

from jsonpath_ng import jsonpath
from jsonpath_ng.ext import parse

data = [
	{"akey":"idcard","group":12},
	{"akey":"uid","group":14},
	{"akey":"name","group":8},
]

[m.value for m in parse("$.[?(@akey='idcard'])").find(data)]

Runtim error is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sunziyi/Documents/py_env/bmtag/lib/python2.7/site-packages/jsonpath_ng/ext/parser.py", line 170, in parse
    return ExtentedJsonPathParser(debug=debug).parse(path)
  File "/Users/sunziyi/Documents/py_env/bmtag/lib/python2.7/site-packages/jsonpath_ng/parser.py", line 32, in parse
    return self.parse_token_stream(lexer.tokenize(string))
  File "/Users/sunziyi/Documents/py_env/bmtag/lib/python2.7/site-packages/jsonpath_ng/parser.py", line 55, in parse_token_stream
    return new_parser.parse(lexer = IteratorToTokenStream(token_iterator))
  File "/Users/sunziyi/Documents/py_env/bmtag/lib/python2.7/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/sunziyi/Documents/py_env/bmtag/lib/python2.7/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/sunziyi/Documents/py_env/bmtag/lib/python2.7/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Users/sunziyi/Documents/py_env/bmtag/lib/python2.7/site-packages/jsonpath_ng/parser.py", line 69, in p_error
    raise Exception('Parse error at %s:%s near token %s (%s)' % (t.lineno, t.col, t.value, t.type))
Exception: Parse error at 1:3 near token ? (?)

Question mark cannot be used?

**Comment by sunziyi** [comment]
I found the reason is that cannot scan array directly. I just wrapped data in a key-value is ok
