### ISSUE TITLE
Unknown named operator `len`

### ISSUE THREAD

**Issue by ailjushkin** [h2non/jsonpath-ng#7]
Installation log:

```
C:\WINDOWS\system32>pip install jsonpath-ng
Collecting jsonpath-ng
  Downloading jsonpath_ng-1.4.3-py2.py3-none-any.whl
Requirement already satisfied: decorator in c:\python27\lib\site-packages (from jsonpath-ng)
Requirement already satisfied: ply in c:\python27\lib\site-packages (from jsonpath-ng)
Requirement already satisfied: six in c:\python27\lib\site-packages (from jsonpath-ng)
Installing collected packages: jsonpath-ng
Successfully installed jsonpath-ng-1.4.3

C:\WINDOWS\system32>pip install -U jsonpath-ng
Requirement already up-to-date: jsonpath-ng in c:\python27\lib\site-packages
Requirement already up-to-date: decorator in c:\python27\lib\site-packages (from jsonpath-ng)
Collecting ply (from jsonpath-ng)
  Downloading ply-3.10.tar.gz (150kB)
    100% |################################| 153kB 1.4MB/s
Collecting six (from jsonpath-ng)
  Downloading six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: ply
  Running setup.py bdist_wheel for ply ... done
  Stored in directory: C:\Users\alexander.iljushkin\AppData\Local\pip\Cache\wheels\ad\dd\ad\8ce1991a7b380dfe23d6cc81a4de5c2775bc728b5a0a7721aa
Successfully built ply
Installing collected packages: ply, six
  Found existing installation: ply 3.8
    Uninstalling ply-3.8:
      Successfully uninstalled ply-3.8
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
Successfully installed ply-3.10 six-1.11.0
```
Script: 

```
# coding: utf-8

import json

import jsonpath_ng as jng
import jsonpath_rw as jrw
import jsonpath_rw_ext as jex

s = u"""
{
"menu": {
    "id": "file",
    "value": "File",
    "popup": {
      "menuitem": [
        {
          "value": "New",
          "onclick": "CreateNewDoc()"
        },
        {
          "value": "Open",
          "onclick": "OpenDoc()"
        },
        {
          "value": "Close",
          "onclick": "CloseDoc()"
        }
      ]
    }
  }
}
"""

if __name__ == '__main__':
    jsonpath_expr = jng.parse("$..menuitem.`len`")
    search = jsonpath_expr.find(json.loads(s))

```

Error:

```
pydev debugger: process 21076 is connecting

Connected to pydev debugger (build 172.3968.37)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/alexander.iljushkin/Desktop/test.py", line 35, in <module>
    jsonpath_expr = jng.parse("$..menuitem.`len`")
  File "C:\Python27\lib\site-packages\jsonpath_ng\parser.py", line 14, in parse
    return JsonPathParser().parse(string)
  File "C:\Python27\lib\site-packages\jsonpath_ng\parser.py", line 32, in parse
    return self.parse_token_stream(lexer.tokenize(string))
  File "C:\Python27\lib\site-packages\jsonpath_ng\parser.py", line 55, in parse_token_stream
    return new_parser.parse(lexer = IteratorToTokenStream(token_iterator))
  File "C:\Python27\lib\site-packages\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Python27\lib\site-packages\ply\yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "C:\Python27\lib\site-packages\jsonpath_ng\parser.py", line 101, in p_jsonpath_named_operator
    raise Exception('Unknown named operator `%s` at %s:%s' % (p[1], p.lineno(1), p.lexpos(1)))
Exception: Unknown named operator `len` at 1:16
```

**Comment by themsquared** [comment]
Confirmed on my end as well. This doesn't seem to exist.

**Comment by dlacher1** [comment]
you want to do from jsonpath.ext import parse. `len` only exists in the extended version

**Comment by shoaibm-aurea** [comment]
just a minor correction, it should be from jsonpath_ng.ext import parse

**Comment by michaelmior** [comment]
Closing as using the extended parser seems to solve this problem.
